# Site settings
name: lanluohaisi's blog
email: ''
author: yuanfang
url: http://www.hifreud.com
resume_site: ''
github: https://lanluohaisi/github.com/
baseurl: ""
description: 人生不是考试，没有标准答案，任何一种职业，一种身份，一种生活状态都有被尊重的理由.
meta_description: lanluohaisi;个人博客;你之所以不开心，是因为你贪心
motto: 人生没有太晚的开始
banner: 欲无后悔先修己，各有前因莫羡人.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: lanluohaisi

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

